files:
  - source: /src/content/en/**/*.*
    translation: /src/content/%locale%/**/%original_file_name%
    content_segmentation: 0
    languages_mapping:
      locale:
        ar: ar
        zh-CN: zh-cn
        zh-TW: zh-tw
        nl: nl
        fr: fr
        de: de
        he: he
        hi: hi
        id: id
        it: it
        ja: ja
        ko: ko
        pl: pl
        pt-BR: pt-br
        ru: ru
        es-ES: es
        th: th
        tr: tr
        vi: vi
